apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: jenkins-udhaya
  name: jenkins-udhaya
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: jenkins-udhaya
  type: NodePort
status:
  loadBalancer: {}
